package cn.edu.xmu.oomall.wechatpay.mapper;

import cn.edu.xmu.oomall.wechatpay.model.po.WeChatPayTransactionPo;
import cn.edu.xmu.oomall.wechatpay.model.po.WeChatPayTransactionPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeChatPayTransactionPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    int insert(WeChatPayTransactionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    int insertSelective(WeChatPayTransactionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    List<WeChatPayTransactionPo> selectByExample(WeChatPayTransactionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    WeChatPayTransactionPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WeChatPayTransactionPo record, @Param("example") WeChatPayTransactionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WeChatPayTransactionPo record, @Param("example") WeChatPayTransactionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeChatPayTransactionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeChatPayTransactionPo record);
}