management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8086
  tomcat:
    threads:
      max: 500

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: goods-service
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 10.30.82.244:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 12345678
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8

  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000

mybatis:
  type-aliases-package: cn.edu.xmu.oomall.goods.model.po
  mapper-locations: classpath*:cn.edu.xmu.oomall.goods.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

oomall:
  goods:
    onsale:
      expiretime: 10000
    product:
      expiretime: 10000

productservice:
  webdav:
    username: ooad_javaee
    password: 12345678
    baseUrl: http://172.16.4.1/webdav/test/
