package cn.edu.xmu.oomall.wechatpay.model.po;

import java.time.LocalDateTime;

public class WeChatPayRefundPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.refund_id
     *
     * @mbg.generated
     */
    private String refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.out_refund_no
     *
     * @mbg.generated
     */
    private String outRefundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.channel
     *
     * @mbg.generated
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.user_received_account
     *
     * @mbg.generated
     */
    private String userReceivedAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.refund
     *
     * @mbg.generated
     */
    private Integer refund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.payer_total
     *
     * @mbg.generated
     */
    private Integer payerTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.payer_refund
     *
     * @mbg.generated
     */
    private Integer payerRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.settlement_refund
     *
     * @mbg.generated
     */
    private Integer settlementRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.settlement_total
     *
     * @mbg.generated
     */
    private Integer settlementTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.discount_refund
     *
     * @mbg.generated
     */
    private Integer discountRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_refund.notify_url
     *
     * @mbg.generated
     */
    private String notifyUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.id
     *
     * @return the value of oomall_wechatpay_refund.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.id
     *
     * @param id the value for oomall_wechatpay_refund.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.refund_id
     *
     * @return the value of oomall_wechatpay_refund.refund_id
     *
     * @mbg.generated
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.refund_id
     *
     * @param refundId the value for oomall_wechatpay_refund.refund_id
     *
     * @mbg.generated
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId == null ? null : refundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.out_refund_no
     *
     * @return the value of oomall_wechatpay_refund.out_refund_no
     *
     * @mbg.generated
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.out_refund_no
     *
     * @param outRefundNo the value for oomall_wechatpay_refund.out_refund_no
     *
     * @mbg.generated
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.transaction_id
     *
     * @return the value of oomall_wechatpay_refund.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.transaction_id
     *
     * @param transactionId the value for oomall_wechatpay_refund.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.out_trade_no
     *
     * @return the value of oomall_wechatpay_refund.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.out_trade_no
     *
     * @param outTradeNo the value for oomall_wechatpay_refund.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.channel
     *
     * @return the value of oomall_wechatpay_refund.channel
     *
     * @mbg.generated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.channel
     *
     * @param channel the value for oomall_wechatpay_refund.channel
     *
     * @mbg.generated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.user_received_account
     *
     * @return the value of oomall_wechatpay_refund.user_received_account
     *
     * @mbg.generated
     */
    public String getUserReceivedAccount() {
        return userReceivedAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.user_received_account
     *
     * @param userReceivedAccount the value for oomall_wechatpay_refund.user_received_account
     *
     * @mbg.generated
     */
    public void setUserReceivedAccount(String userReceivedAccount) {
        this.userReceivedAccount = userReceivedAccount == null ? null : userReceivedAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.create_time
     *
     * @return the value of oomall_wechatpay_refund.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.create_time
     *
     * @param createTime the value for oomall_wechatpay_refund.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.status
     *
     * @return the value of oomall_wechatpay_refund.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.status
     *
     * @param status the value for oomall_wechatpay_refund.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.total
     *
     * @return the value of oomall_wechatpay_refund.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.total
     *
     * @param total the value for oomall_wechatpay_refund.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.refund
     *
     * @return the value of oomall_wechatpay_refund.refund
     *
     * @mbg.generated
     */
    public Integer getRefund() {
        return refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.refund
     *
     * @param refund the value for oomall_wechatpay_refund.refund
     *
     * @mbg.generated
     */
    public void setRefund(Integer refund) {
        this.refund = refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.payer_total
     *
     * @return the value of oomall_wechatpay_refund.payer_total
     *
     * @mbg.generated
     */
    public Integer getPayerTotal() {
        return payerTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.payer_total
     *
     * @param payerTotal the value for oomall_wechatpay_refund.payer_total
     *
     * @mbg.generated
     */
    public void setPayerTotal(Integer payerTotal) {
        this.payerTotal = payerTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.payer_refund
     *
     * @return the value of oomall_wechatpay_refund.payer_refund
     *
     * @mbg.generated
     */
    public Integer getPayerRefund() {
        return payerRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.payer_refund
     *
     * @param payerRefund the value for oomall_wechatpay_refund.payer_refund
     *
     * @mbg.generated
     */
    public void setPayerRefund(Integer payerRefund) {
        this.payerRefund = payerRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.settlement_refund
     *
     * @return the value of oomall_wechatpay_refund.settlement_refund
     *
     * @mbg.generated
     */
    public Integer getSettlementRefund() {
        return settlementRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.settlement_refund
     *
     * @param settlementRefund the value for oomall_wechatpay_refund.settlement_refund
     *
     * @mbg.generated
     */
    public void setSettlementRefund(Integer settlementRefund) {
        this.settlementRefund = settlementRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.settlement_total
     *
     * @return the value of oomall_wechatpay_refund.settlement_total
     *
     * @mbg.generated
     */
    public Integer getSettlementTotal() {
        return settlementTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.settlement_total
     *
     * @param settlementTotal the value for oomall_wechatpay_refund.settlement_total
     *
     * @mbg.generated
     */
    public void setSettlementTotal(Integer settlementTotal) {
        this.settlementTotal = settlementTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.discount_refund
     *
     * @return the value of oomall_wechatpay_refund.discount_refund
     *
     * @mbg.generated
     */
    public Integer getDiscountRefund() {
        return discountRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.discount_refund
     *
     * @param discountRefund the value for oomall_wechatpay_refund.discount_refund
     *
     * @mbg.generated
     */
    public void setDiscountRefund(Integer discountRefund) {
        this.discountRefund = discountRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.currency
     *
     * @return the value of oomall_wechatpay_refund.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.currency
     *
     * @param currency the value for oomall_wechatpay_refund.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.reason
     *
     * @return the value of oomall_wechatpay_refund.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.reason
     *
     * @param reason the value for oomall_wechatpay_refund.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_refund.notify_url
     *
     * @return the value of oomall_wechatpay_refund.notify_url
     *
     * @mbg.generated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_refund.notify_url
     *
     * @param notifyUrl the value for oomall_wechatpay_refund.notify_url
     *
     * @mbg.generated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }
}