package cn.edu.xmu.oomall.wechatpay.model.po;

import java.time.LocalDateTime;

public class WeChatPayTransactionPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.appid
     *
     * @mbg.generated
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.mchid
     *
     * @mbg.generated
     */
    private String mchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.trade_type
     *
     * @mbg.generated
     */
    private String tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.trade_state
     *
     * @mbg.generated
     */
    private String tradeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.trade_state_desc
     *
     * @mbg.generated
     */
    private String tradeStateDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.payer_total
     *
     * @mbg.generated
     */
    private Integer payerTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.payer_currency
     *
     * @mbg.generated
     */
    private String payerCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.success_time
     *
     * @mbg.generated
     */
    private LocalDateTime successTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.time_expire
     *
     * @mbg.generated
     */
    private LocalDateTime timeExpire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.notify_url
     *
     * @mbg.generated
     */
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_wechatpay_transaction.prepay_id
     *
     * @mbg.generated
     */
    private String prepayId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.id
     *
     * @return the value of oomall_wechatpay_transaction.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.id
     *
     * @param id the value for oomall_wechatpay_transaction.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.appid
     *
     * @return the value of oomall_wechatpay_transaction.appid
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.appid
     *
     * @param appid the value for oomall_wechatpay_transaction.appid
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.mchid
     *
     * @return the value of oomall_wechatpay_transaction.mchid
     *
     * @mbg.generated
     */
    public String getMchid() {
        return mchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.mchid
     *
     * @param mchid the value for oomall_wechatpay_transaction.mchid
     *
     * @mbg.generated
     */
    public void setMchid(String mchid) {
        this.mchid = mchid == null ? null : mchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.out_trade_no
     *
     * @return the value of oomall_wechatpay_transaction.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.out_trade_no
     *
     * @param outTradeNo the value for oomall_wechatpay_transaction.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.transaction_id
     *
     * @return the value of oomall_wechatpay_transaction.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.transaction_id
     *
     * @param transactionId the value for oomall_wechatpay_transaction.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.trade_type
     *
     * @return the value of oomall_wechatpay_transaction.trade_type
     *
     * @mbg.generated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.trade_type
     *
     * @param tradeType the value for oomall_wechatpay_transaction.trade_type
     *
     * @mbg.generated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.trade_state
     *
     * @return the value of oomall_wechatpay_transaction.trade_state
     *
     * @mbg.generated
     */
    public String getTradeState() {
        return tradeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.trade_state
     *
     * @param tradeState the value for oomall_wechatpay_transaction.trade_state
     *
     * @mbg.generated
     */
    public void setTradeState(String tradeState) {
        this.tradeState = tradeState == null ? null : tradeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.trade_state_desc
     *
     * @return the value of oomall_wechatpay_transaction.trade_state_desc
     *
     * @mbg.generated
     */
    public String getTradeStateDesc() {
        return tradeStateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.trade_state_desc
     *
     * @param tradeStateDesc the value for oomall_wechatpay_transaction.trade_state_desc
     *
     * @mbg.generated
     */
    public void setTradeStateDesc(String tradeStateDesc) {
        this.tradeStateDesc = tradeStateDesc == null ? null : tradeStateDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.total
     *
     * @return the value of oomall_wechatpay_transaction.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.total
     *
     * @param total the value for oomall_wechatpay_transaction.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.payer_total
     *
     * @return the value of oomall_wechatpay_transaction.payer_total
     *
     * @mbg.generated
     */
    public Integer getPayerTotal() {
        return payerTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.payer_total
     *
     * @param payerTotal the value for oomall_wechatpay_transaction.payer_total
     *
     * @mbg.generated
     */
    public void setPayerTotal(Integer payerTotal) {
        this.payerTotal = payerTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.currency
     *
     * @return the value of oomall_wechatpay_transaction.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.currency
     *
     * @param currency the value for oomall_wechatpay_transaction.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.payer_currency
     *
     * @return the value of oomall_wechatpay_transaction.payer_currency
     *
     * @mbg.generated
     */
    public String getPayerCurrency() {
        return payerCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.payer_currency
     *
     * @param payerCurrency the value for oomall_wechatpay_transaction.payer_currency
     *
     * @mbg.generated
     */
    public void setPayerCurrency(String payerCurrency) {
        this.payerCurrency = payerCurrency == null ? null : payerCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.openid
     *
     * @return the value of oomall_wechatpay_transaction.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.openid
     *
     * @param openid the value for oomall_wechatpay_transaction.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.success_time
     *
     * @return the value of oomall_wechatpay_transaction.success_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.success_time
     *
     * @param successTime the value for oomall_wechatpay_transaction.success_time
     *
     * @mbg.generated
     */
    public void setSuccessTime(LocalDateTime successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.description
     *
     * @return the value of oomall_wechatpay_transaction.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.description
     *
     * @param description the value for oomall_wechatpay_transaction.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.time_expire
     *
     * @return the value of oomall_wechatpay_transaction.time_expire
     *
     * @mbg.generated
     */
    public LocalDateTime getTimeExpire() {
        return timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.time_expire
     *
     * @param timeExpire the value for oomall_wechatpay_transaction.time_expire
     *
     * @mbg.generated
     */
    public void setTimeExpire(LocalDateTime timeExpire) {
        this.timeExpire = timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.notify_url
     *
     * @return the value of oomall_wechatpay_transaction.notify_url
     *
     * @mbg.generated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.notify_url
     *
     * @param notifyUrl the value for oomall_wechatpay_transaction.notify_url
     *
     * @mbg.generated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_wechatpay_transaction.prepay_id
     *
     * @return the value of oomall_wechatpay_transaction.prepay_id
     *
     * @mbg.generated
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_wechatpay_transaction.prepay_id
     *
     * @param prepayId the value for oomall_wechatpay_transaction.prepay_id
     *
     * @mbg.generated
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }
}