package cn.edu.xmu.oomall.wechatpay.model.po;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class WeChatPayRefundPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public WeChatPayRefundPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRefundIdIsNull() {
            addCriterion("`refund_id` is null");
            return (Criteria) this;
        }

        public Criteria andRefundIdIsNotNull() {
            addCriterion("`refund_id` is not null");
            return (Criteria) this;
        }

        public Criteria andRefundIdEqualTo(String value) {
            addCriterion("`refund_id` =", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdNotEqualTo(String value) {
            addCriterion("`refund_id` <>", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdGreaterThan(String value) {
            addCriterion("`refund_id` >", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdGreaterThanOrEqualTo(String value) {
            addCriterion("`refund_id` >=", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdLessThan(String value) {
            addCriterion("`refund_id` <", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdLessThanOrEqualTo(String value) {
            addCriterion("`refund_id` <=", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdLike(String value) {
            addCriterion("`refund_id` like", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdNotLike(String value) {
            addCriterion("`refund_id` not like", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdIn(List<String> values) {
            addCriterion("`refund_id` in", values, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdNotIn(List<String> values) {
            addCriterion("`refund_id` not in", values, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdBetween(String value1, String value2) {
            addCriterion("`refund_id` between", value1, value2, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdNotBetween(String value1, String value2) {
            addCriterion("`refund_id` not between", value1, value2, "refundId");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoIsNull() {
            addCriterion("`out_refund_no` is null");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoIsNotNull() {
            addCriterion("`out_refund_no` is not null");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoEqualTo(String value) {
            addCriterion("`out_refund_no` =", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoNotEqualTo(String value) {
            addCriterion("`out_refund_no` <>", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoGreaterThan(String value) {
            addCriterion("`out_refund_no` >", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoGreaterThanOrEqualTo(String value) {
            addCriterion("`out_refund_no` >=", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoLessThan(String value) {
            addCriterion("`out_refund_no` <", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoLessThanOrEqualTo(String value) {
            addCriterion("`out_refund_no` <=", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoLike(String value) {
            addCriterion("`out_refund_no` like", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoNotLike(String value) {
            addCriterion("`out_refund_no` not like", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoIn(List<String> values) {
            addCriterion("`out_refund_no` in", values, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoNotIn(List<String> values) {
            addCriterion("`out_refund_no` not in", values, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoBetween(String value1, String value2) {
            addCriterion("`out_refund_no` between", value1, value2, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoNotBetween(String value1, String value2) {
            addCriterion("`out_refund_no` not between", value1, value2, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNull() {
            addCriterion("`transaction_id` is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNotNull() {
            addCriterion("`transaction_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdEqualTo(String value) {
            addCriterion("`transaction_id` =", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotEqualTo(String value) {
            addCriterion("`transaction_id` <>", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThan(String value) {
            addCriterion("`transaction_id` >", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("`transaction_id` >=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThan(String value) {
            addCriterion("`transaction_id` <", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("`transaction_id` <=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLike(String value) {
            addCriterion("`transaction_id` like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotLike(String value) {
            addCriterion("`transaction_id` not like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIn(List<String> values) {
            addCriterion("`transaction_id` in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotIn(List<String> values) {
            addCriterion("`transaction_id` not in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdBetween(String value1, String value2) {
            addCriterion("`transaction_id` between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotBetween(String value1, String value2) {
            addCriterion("`transaction_id` not between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNull() {
            addCriterion("`out_trade_no` is null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNotNull() {
            addCriterion("`out_trade_no` is not null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoEqualTo(String value) {
            addCriterion("`out_trade_no` =", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotEqualTo(String value) {
            addCriterion("`out_trade_no` <>", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThan(String value) {
            addCriterion("`out_trade_no` >", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("`out_trade_no` >=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThan(String value) {
            addCriterion("`out_trade_no` <", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
            addCriterion("`out_trade_no` <=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLike(String value) {
            addCriterion("`out_trade_no` like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotLike(String value) {
            addCriterion("`out_trade_no` not like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIn(List<String> values) {
            addCriterion("`out_trade_no` in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotIn(List<String> values) {
            addCriterion("`out_trade_no` not in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoBetween(String value1, String value2) {
            addCriterion("`out_trade_no` between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotBetween(String value1, String value2) {
            addCriterion("`out_trade_no` not between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("`channel` is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("`channel` is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("`channel` =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("`channel` <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("`channel` >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("`channel` >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("`channel` <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("`channel` <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("`channel` like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("`channel` not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("`channel` in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("`channel` not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("`channel` between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("`channel` not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountIsNull() {
            addCriterion("`user_received_account` is null");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountIsNotNull() {
            addCriterion("`user_received_account` is not null");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountEqualTo(String value) {
            addCriterion("`user_received_account` =", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountNotEqualTo(String value) {
            addCriterion("`user_received_account` <>", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountGreaterThan(String value) {
            addCriterion("`user_received_account` >", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountGreaterThanOrEqualTo(String value) {
            addCriterion("`user_received_account` >=", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountLessThan(String value) {
            addCriterion("`user_received_account` <", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountLessThanOrEqualTo(String value) {
            addCriterion("`user_received_account` <=", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountLike(String value) {
            addCriterion("`user_received_account` like", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountNotLike(String value) {
            addCriterion("`user_received_account` not like", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountIn(List<String> values) {
            addCriterion("`user_received_account` in", values, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountNotIn(List<String> values) {
            addCriterion("`user_received_account` not in", values, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountBetween(String value1, String value2) {
            addCriterion("`user_received_account` between", value1, value2, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountNotBetween(String value1, String value2) {
            addCriterion("`user_received_account` not between", value1, value2, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("`total` is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("`total` is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(Integer value) {
            addCriterion("`total` =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(Integer value) {
            addCriterion("`total` <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(Integer value) {
            addCriterion("`total` >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`total` >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(Integer value) {
            addCriterion("`total` <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(Integer value) {
            addCriterion("`total` <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<Integer> values) {
            addCriterion("`total` in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<Integer> values) {
            addCriterion("`total` not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(Integer value1, Integer value2) {
            addCriterion("`total` between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("`total` not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andRefundIsNull() {
            addCriterion("`refund` is null");
            return (Criteria) this;
        }

        public Criteria andRefundIsNotNull() {
            addCriterion("`refund` is not null");
            return (Criteria) this;
        }

        public Criteria andRefundEqualTo(Integer value) {
            addCriterion("`refund` =", value, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundNotEqualTo(Integer value) {
            addCriterion("`refund` <>", value, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundGreaterThan(Integer value) {
            addCriterion("`refund` >", value, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundGreaterThanOrEqualTo(Integer value) {
            addCriterion("`refund` >=", value, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundLessThan(Integer value) {
            addCriterion("`refund` <", value, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundLessThanOrEqualTo(Integer value) {
            addCriterion("`refund` <=", value, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundIn(List<Integer> values) {
            addCriterion("`refund` in", values, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundNotIn(List<Integer> values) {
            addCriterion("`refund` not in", values, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundBetween(Integer value1, Integer value2) {
            addCriterion("`refund` between", value1, value2, "refund");
            return (Criteria) this;
        }

        public Criteria andRefundNotBetween(Integer value1, Integer value2) {
            addCriterion("`refund` not between", value1, value2, "refund");
            return (Criteria) this;
        }

        public Criteria andPayerTotalIsNull() {
            addCriterion("`payer_total` is null");
            return (Criteria) this;
        }

        public Criteria andPayerTotalIsNotNull() {
            addCriterion("`payer_total` is not null");
            return (Criteria) this;
        }

        public Criteria andPayerTotalEqualTo(Integer value) {
            addCriterion("`payer_total` =", value, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalNotEqualTo(Integer value) {
            addCriterion("`payer_total` <>", value, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalGreaterThan(Integer value) {
            addCriterion("`payer_total` >", value, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`payer_total` >=", value, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalLessThan(Integer value) {
            addCriterion("`payer_total` <", value, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalLessThanOrEqualTo(Integer value) {
            addCriterion("`payer_total` <=", value, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalIn(List<Integer> values) {
            addCriterion("`payer_total` in", values, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalNotIn(List<Integer> values) {
            addCriterion("`payer_total` not in", values, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalBetween(Integer value1, Integer value2) {
            addCriterion("`payer_total` between", value1, value2, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("`payer_total` not between", value1, value2, "payerTotal");
            return (Criteria) this;
        }

        public Criteria andPayerRefundIsNull() {
            addCriterion("`payer_refund` is null");
            return (Criteria) this;
        }

        public Criteria andPayerRefundIsNotNull() {
            addCriterion("`payer_refund` is not null");
            return (Criteria) this;
        }

        public Criteria andPayerRefundEqualTo(Integer value) {
            addCriterion("`payer_refund` =", value, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundNotEqualTo(Integer value) {
            addCriterion("`payer_refund` <>", value, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundGreaterThan(Integer value) {
            addCriterion("`payer_refund` >", value, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundGreaterThanOrEqualTo(Integer value) {
            addCriterion("`payer_refund` >=", value, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundLessThan(Integer value) {
            addCriterion("`payer_refund` <", value, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundLessThanOrEqualTo(Integer value) {
            addCriterion("`payer_refund` <=", value, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundIn(List<Integer> values) {
            addCriterion("`payer_refund` in", values, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundNotIn(List<Integer> values) {
            addCriterion("`payer_refund` not in", values, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundBetween(Integer value1, Integer value2) {
            addCriterion("`payer_refund` between", value1, value2, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andPayerRefundNotBetween(Integer value1, Integer value2) {
            addCriterion("`payer_refund` not between", value1, value2, "payerRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundIsNull() {
            addCriterion("`settlement_refund` is null");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundIsNotNull() {
            addCriterion("`settlement_refund` is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundEqualTo(Integer value) {
            addCriterion("`settlement_refund` =", value, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundNotEqualTo(Integer value) {
            addCriterion("`settlement_refund` <>", value, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundGreaterThan(Integer value) {
            addCriterion("`settlement_refund` >", value, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundGreaterThanOrEqualTo(Integer value) {
            addCriterion("`settlement_refund` >=", value, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundLessThan(Integer value) {
            addCriterion("`settlement_refund` <", value, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundLessThanOrEqualTo(Integer value) {
            addCriterion("`settlement_refund` <=", value, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundIn(List<Integer> values) {
            addCriterion("`settlement_refund` in", values, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundNotIn(List<Integer> values) {
            addCriterion("`settlement_refund` not in", values, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundBetween(Integer value1, Integer value2) {
            addCriterion("`settlement_refund` between", value1, value2, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementRefundNotBetween(Integer value1, Integer value2) {
            addCriterion("`settlement_refund` not between", value1, value2, "settlementRefund");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalIsNull() {
            addCriterion("`settlement_total` is null");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalIsNotNull() {
            addCriterion("`settlement_total` is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalEqualTo(Integer value) {
            addCriterion("`settlement_total` =", value, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalNotEqualTo(Integer value) {
            addCriterion("`settlement_total` <>", value, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalGreaterThan(Integer value) {
            addCriterion("`settlement_total` >", value, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`settlement_total` >=", value, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalLessThan(Integer value) {
            addCriterion("`settlement_total` <", value, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalLessThanOrEqualTo(Integer value) {
            addCriterion("`settlement_total` <=", value, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalIn(List<Integer> values) {
            addCriterion("`settlement_total` in", values, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalNotIn(List<Integer> values) {
            addCriterion("`settlement_total` not in", values, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalBetween(Integer value1, Integer value2) {
            addCriterion("`settlement_total` between", value1, value2, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andSettlementTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("`settlement_total` not between", value1, value2, "settlementTotal");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundIsNull() {
            addCriterion("`discount_refund` is null");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundIsNotNull() {
            addCriterion("`discount_refund` is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundEqualTo(Integer value) {
            addCriterion("`discount_refund` =", value, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundNotEqualTo(Integer value) {
            addCriterion("`discount_refund` <>", value, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundGreaterThan(Integer value) {
            addCriterion("`discount_refund` >", value, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundGreaterThanOrEqualTo(Integer value) {
            addCriterion("`discount_refund` >=", value, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundLessThan(Integer value) {
            addCriterion("`discount_refund` <", value, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundLessThanOrEqualTo(Integer value) {
            addCriterion("`discount_refund` <=", value, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundIn(List<Integer> values) {
            addCriterion("`discount_refund` in", values, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundNotIn(List<Integer> values) {
            addCriterion("`discount_refund` not in", values, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundBetween(Integer value1, Integer value2) {
            addCriterion("`discount_refund` between", value1, value2, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andDiscountRefundNotBetween(Integer value1, Integer value2) {
            addCriterion("`discount_refund` not between", value1, value2, "discountRefund");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNull() {
            addCriterion("`currency` is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNotNull() {
            addCriterion("`currency` is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyEqualTo(String value) {
            addCriterion("`currency` =", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotEqualTo(String value) {
            addCriterion("`currency` <>", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThan(String value) {
            addCriterion("`currency` >", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("`currency` >=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThan(String value) {
            addCriterion("`currency` <", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThanOrEqualTo(String value) {
            addCriterion("`currency` <=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLike(String value) {
            addCriterion("`currency` like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotLike(String value) {
            addCriterion("`currency` not like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyIn(List<String> values) {
            addCriterion("`currency` in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotIn(List<String> values) {
            addCriterion("`currency` not in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyBetween(String value1, String value2) {
            addCriterion("`currency` between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotBetween(String value1, String value2) {
            addCriterion("`currency` not between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("`reason` is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("`reason` is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("`reason` =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("`reason` <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("`reason` >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("`reason` >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("`reason` <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("`reason` <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("`reason` like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("`reason` not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("`reason` in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("`reason` not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("`reason` between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("`reason` not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIsNull() {
            addCriterion("`notify_url` is null");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIsNotNull() {
            addCriterion("`notify_url` is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlEqualTo(String value) {
            addCriterion("`notify_url` =", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotEqualTo(String value) {
            addCriterion("`notify_url` <>", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlGreaterThan(String value) {
            addCriterion("`notify_url` >", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlGreaterThanOrEqualTo(String value) {
            addCriterion("`notify_url` >=", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLessThan(String value) {
            addCriterion("`notify_url` <", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLessThanOrEqualTo(String value) {
            addCriterion("`notify_url` <=", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLike(String value) {
            addCriterion("`notify_url` like", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotLike(String value) {
            addCriterion("`notify_url` not like", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIn(List<String> values) {
            addCriterion("`notify_url` in", values, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotIn(List<String> values) {
            addCriterion("`notify_url` not in", values, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlBetween(String value1, String value2) {
            addCriterion("`notify_url` between", value1, value2, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotBetween(String value1, String value2) {
            addCriterion("`notify_url` not between", value1, value2, "notifyUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_wechatpay_refund
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}