management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8085
  tomcat:
    threads:
      max: 500


spring:
  application:
    name: coupon-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.175:8888
        group: GXC
        namespace: GXC
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.2.142:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8
  redis:
    database: 0
    host: 172.16.2.142
    port: 6379
#    password: 123456
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000

mybatis:
  type-aliases-package: cn.edu.xmu.oomall.coupon.model.po
  mapper-locations: classpath*:cn.edu.xmu.oomall.coupon.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

#apache:
#  name-server: 81.68.173.165:9876
#  rocketmq:
#    #消费者的配置
#    consumer:
#      pushConsumer: coupon-consumer

oomall:
  coupon:
    webdav:
      user: ooad_javaee
      password: 12345678
      baseurl: http://81.68.173.165/webdav/test/

    bo:
      # Bo在Redis中失效秒数
      expiretime: 600
    list:
      # list对象在Redis中失效毫秒数
      expiretime: 50
      # list对象默认的长度
      defaultsize: 100
ribbon:
  # 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000
#
#  eager-load:
#    enabled: true
feign:
  hystrix:
    enabled: true